language: python

python:
  - 3.5.2

addons:
  apt:
    packages:
    - graphviz

install:
  - pip install -r requirements.txt

script:
  - make clean test doc
  - bin/decompile.py --help
  - bin/decompile.py -n -v -a examples/dao_hack.dasm
  - bin/decompile.py -n -v -a examples/mem_leak.dasm
  - bin/decompile.py -n -v -a examples/withdraw_dao.dasm
  - bin/decompile.py -n -v examples/dao_hack.hex
  - bin/decompile.py -n -v examples/mem_leak.hex
  - bin/decompile.py -n -v examples/withdraw_dao.hex
  - bin/decompile.py -n -v -b examples/dao_hack.hex
  - bin/decompile.py -n -v -b examples/mem_leak.hex
  - bin/decompile.py -n -v -b examples/withdraw_dao.hex
  - bash -c '[ ! -f graph.pdf ]'
  - bash -c '[ ! -d tsv ]'
  - bin/decompile.py -n -v -g graph.pdf -t tsv -d -b examples/dao_hack.hex
  - bash -c '[ -s graph.pdf ]'
  - bash -c '[ -d tsv ]'
  - bash -c '[ -s tsv/block.facts ]'
  - bash -c '[ -s tsv/def.facts ]'
  - bash -c '[ -s tsv/use.facts ]'
  - bash -c '[ -s tsv/edge.facts ]'
  - bash -c '[ -s tsv/entry.facts ]'
  - bash -c '[ -s tsv/exit.facts ]'
  - bash -c '[ -s tsv/op.facts ]'
  - bash -c '[ -s tsv/value.facts ]'
  - bash -c '[ -s tsv/dom.facts ]'
  - bash -c '[ -s tsv/imdom.facts ]'
  - bash -c '[ -s tsv/pdom.facts ]'
  - bash -c '[ -s tsv/impdom.facts ]'
  - bin/disassemble.py examples/basic.hex
  - bin/disassemble.py -p examples/basic.hex
  - bin/disassemble.py examples/dao_hack.hex | bin/decompile.py -n -v -a
  - bash -c '[ ! -f basic.tac ]'
  - bin/decompile.py -a examples/basic.dasm basic.tac
  - bash -c '[ -s basic.tac ]'

notifications:
  slack:
    secure: nTGhXsff6OGZME1QTZ5iGVxUS/4hzBkSQsF0PFPmRpLU1tgJOGh9XylXRnUqhcZXhoKMwfneBZR3gORUdmGHwYsODFq4P98o7K6aiS3TwRDsGczB3X7jFf4kDumTB3P/tJMHczdlQ4pBfQQrzvp09zAv7TOCyUgpCUyTls34L7ZPfgf9xskvXtpdGUg53Emy1FQiM0MvVsoVzXxDj3i1Zk3884SoyBbLyFir+OS+12831b3JASGxcT2BNAJiJ5HChWfDiVX6sigfWi4wB/XXafi5IW3EkVOJa+HP4v4qfBPjvKriWfKC4SGomimfSsk33/PnvcZ/eKrfSPx7HvosX+8koRewLQUnKtLeEQtoNL6eTsXp2bp8TOOd7wqCBKNsklAkJiB44lBgxmItgRdCz5xRBZ2w5K5W6fTdcdzhUevL2Q9fujQh97k+TeTneqaZM3Xorn8pdVH3bSjmpizcgOXCBjc5SkIuCIpxwlJSV+bj8Nvbnaqrr62cOVhc3Awdcss3GdkAi6vrdSwcKmcEmr2Xdh3GXjOnVd2yLXBH4sWrREoVn01XCWSTqY5ZxD733MUX2wMoRtY7/oABLb44rvDXsAZOn4yk9GJc+vDAHHncmNN9mzKWwfOYjYGWF9UnR6FH80GJ0isRqPnpfTnWWeb+pCsNKs+7uTkEjk135mw=
  email: false
